### ISSUE TITLE
A lot of error on script

### ISSUE THREAD

**Issue by tpklge** [thenickdude/proxmox-on-ec2#3]
First part:
[   22.526467] cloud-init[407]: The key fingerprint is:
[   22.527467] cloud-init[407]: SHA256:hG35x2bHXj8COUxn1THsj0uGJpGXeeQAuwUt2ZCGmOU root@proxmox
[   22.530590] cloud-init[407]: The key's randomart image is:
[   22.531622] cloud-init[407]: +---[RSA 3072]----+
[FAILED] Failed to start cloud-init…it job (metadata service crawler).
See 'systemctl status cloud-init.service' for details.
[   22.630011] cloud-init[407]: |       +..+B  .+o|
[  OK  ] Reached target cloud-confi…t - Cloud-config availability.
[   22.676292] cloud-init[407]: |      o+..=o+ o.o|
[  OK  ] Reached target network-online.target - Network is Online.
[   22.732063] cloud-init[407]: |      . E..+.O.  |

Second Part
[   82.126585] cloud-init[555]: Configuration file '/etc/dnsmasq.conf'
[   82.126634] cloud-init[555]:  ==> File on system created by you or by a script.
[   82.126724] cloud-init[555]:  ==> File also in package provided by package maintainer.
[   82.126756] cloud-init[555]:  ==> Using current old file as you requested.
[   82.323090] cloud-init[555]: Created symlink /etc/systemd/system/multi-user.target.wants/dnsmasq.service → /lib/systemd/system/dnsmasq.service.
         Starting dnsmasq.serviceght DHCP and caching DNS server...
[FAILED] Failed to start dnsmasq.se…eight DHCP and caching DNS server.
See 'systemctl status dnsmasq.service' for details.
[   82.791896] cloud-init[555]: Job for dnsmasq.service failed because the control process exited with error code.
[   82.791973] cloud-init[555]: See "systemctl status dnsmasq.service" and "journalctl -xeu dnsmasq.service" for details.
[   82.793628] cloud-init[555]: invoke-rc.d: initscript dnsmasq, action "start" failed.
[   82.799900] cloud-init[555]: × dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
[   82.800118] cloud-init[555]:      Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled; preset: enabled)
[   82.800175] cloud-init[555]:      Active: failed (Result: exit-code) since Sat 2023-08-26 14:19:22 UTC; 9ms ago
[   82.800209] cloud-init[555]:     Process: 8717 ExecStartPre=/etc/init.d/dnsmasq checkconfig (code=exited, status=0/SUCCESS)
[   82.800239] cloud-init[555]:     Process: 8724 ExecStart=/etc/init.d/dnsmasq systemd-exec (code=exited, status=2)
[   82.800269] cloud-init[555]:         CPU: 32ms
[   82.800732] cloud-init[555]: 
[   82.800893] cloud-init[555]: Aug 26 14:19:22 proxmox systemd[1]: Starting dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server...
[   82.800964] cloud-init[555]: Aug 26 14:19:22 proxmox dnsmasq[8724]: dnsmasq: failed to create listening socket for port 53: Address already in use
[   82.801085] cloud-init[555]: Aug 26 14:19:22 proxmox dnsmasq[8724]: failed to create listening socket for port 53: Address already in use
[   82.801143] cloud-init[555]: Aug 26 14:19:22 proxmox dnsmasq[8724]: FAILED to start up
[   82.801194] cloud-init[555]: Aug 26 14:19:22 proxmox systemd[1]: dnsmasq.service: Control process exited, code=exited, status=2/INVALIDARGUMENT
[   82.801292] cloud-init[555]: Aug 26 14:19:22 proxmox systemd[1]: dnsmasq.service: Failed with result 'exit-code'.
[   82.801347] cloud-init[555]: Aug 26 14:19:22 proxmox systemd[1]: Failed to start dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server.
[   82.812760] cloud-init[555]: Processing triggers for libc-bin (2.36-9+deb12u1) ...
[   82.845280] cloud-init[555]: Processing triggers for man-db (2.11.2-2) ...
[   83.418701] cloud-init[555]: Processing triggers for dbus (1.14.8-2~deb12u1) ...

Third part

[   82.126585] cloud-init[555]: Configuration file '/etc/dnsmasq.conf'
[   82.126634] cloud-init[555]:  ==> File on system created by you or by a script.
[   82.126724] cloud-init[555]:  ==> File also in package provided by package maintainer.
[   82.126756] cloud-init[555]:  ==> Using current old file as you requested.
[   82.323090] cloud-init[555]: Created symlink /etc/systemd/system/multi-user.target.wants/dnsmasq.service → /lib/systemd/system/dnsmasq.service.
         Starting dnsmasq.serviceght DHCP and caching DNS server...
[FAILED] Failed to start dnsmasq.se…eight DHCP and caching DNS server.
See 'systemctl status dnsmasq.service' for details.
[   82.791896] cloud-init[555]: Job for dnsmasq.service failed because the control process exited with error code.
[   82.791973] cloud-init[555]: See "systemctl status dnsmasq.service" and "journalctl -xeu dnsmasq.service" for details.
[   82.793628] cloud-init[555]: invoke-rc.d: initscript dnsmasq, action "start" failed.
[   82.799900] cloud-init[555]: × dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
[   82.800118] cloud-init[555]:      Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled; preset: enabled)
[   82.800175] cloud-init[555]:      Active: failed (Result: exit-code) since Sat 2023-08-26 14:19:22 UTC; 9ms ago
[   82.800209] cloud-init[555]:     Process: 8717 ExecStartPre=/etc/init.d/dnsmasq checkconfig (code=exited, status=0/SUCCESS)
[   82.800239] cloud-init[555]:     Process: 8724 ExecStart=/etc/init.d/dnsmasq systemd-exec (code=exited, status=2)
[   82.800269] cloud-init[555]:         CPU: 32ms
[   82.800732] cloud-init[555]: 
[   82.800893] cloud-init[555]: Aug 26 14:19:22 proxmox systemd[1]: Starting dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server...
[   82.800964] cloud-init[555]: Aug 26 14:19:22 proxmox dnsmasq[8724]: dnsmasq: failed to create listening socket for port 53: Address already in use
[   82.801085] cloud-init[555]: Aug 26 14:19:22 proxmox dnsmasq[8724]: failed to create listening socket for port 53: Address already in use
[   82.801143] cloud-init[555]: Aug 26 14:19:22 proxmox dnsmasq[8724]: FAILED to start up
[   82.801194] cloud-init[555]: Aug 26 14:19:22 proxmox systemd[1]: dnsmasq.service: Control process exited, code=exited, status=2/INVALIDARGUMENT
[   82.801292] cloud-init[555]: Aug 26 14:19:22 proxmox systemd[1]: dnsmasq.service: Failed with result 'exit-code'.
[   82.801347] cloud-init[555]: Aug 26 14:19:22 proxmox systemd[1]: Failed to start dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server.
[   82.812760] cloud-init[555]: Processing triggers for libc-bin (2.36-9+deb12u1) ...
[   82.845280] cloud-init[555]: Processing triggers for man-db (2.11.2-2) ...
[   83.418701] cloud-init[555]: Processing triggers for dbus (1.14.8-2~deb12u1) ...

I use Debian 12, the unique debian ami in AWS ate 2023.

**Comment by thenickdude** [comment]
Debian 12 not supported, use 11
